import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Instagram from "../components/Instagram";
import Navbar from "../components/Navbar";
import Slider from "../components/Slider";
import { SliderData } from "../components/SliderData";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Fastrvl Argentina</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Hero
				heading="Descubre Argentina"
				message="Rápida organización, óptima satisfacción"
			/>
			<Slider slides={SliderData} />
			<Instagram />
		</div>
	);
}
